# Performs detailed logging
debug: false

# Database Backend
# Possible selections: sqlite, disable
db: sqlite

# Default data.db
db_file: data.db

# Search result list count limitor. -1 is unlimited.
search_limitor: -1

# Record tracks
record: false

# Recorded sounds folder
rec_folder: ./recs/

# Item count per pages in queue command
queue_pager: 8

# Maximum volume, sound distortion may occur when the volume is above 100
maximum_volume: 100