debug: false

# Default sqlite. just set it to false to disable it
# Possible selections: sqlite, disable
db: sqlite

# Default data.db
dbFile: data.db

# Search result list count limitor. -1 is unlimited.
searchLimitor: -1

# Record tracks
record: true

# Recorded sounds folder
recFolder: ./recs/

# Item count per pages in queue command
queuePager: 8