debug: false

# Default sqlite. just set it to false to disable it
# Possible selections: sqlite, disable
db: sqlite

# Default data.db
db_file: data.db

# Search result list count limitor. -1 is unlimited.
search_limitor: -1

# Record tracks
record: true

# Recorded sounds folder
rec_folder: ./recs/

# Item count per pages in queue command
queue_pager: 8

# Maximum volume
maximum_volume: 150